### ISSUE TITLE
Usage of mapState with TypeScript in vue

### ISSUE THREAD

**Issue by arunrreddy** [alexander-heimbuch/redux-vuex#10]
I am trying to access a state variable using typescript. I am unable to get it to work. This is what I have so far.
```typescript
<script type="ts">
interface Auth {
 accessToken?: string;
 expiresAt?: number;
 authenticated?: boolean;
}
import { mapState } from 'redux-vuex';
import { Vue, Component } from 'vue-property-decorator';
export default class Example extends Vue {
  private auth: Auth = mapState({
    auth: 'auth'
  })
}
</script>
```
When I try to access the auth variable using this.auth, I am being returned a function instead of the contents of the state object 'auth'. What is the right way of accessing this state variable if using typescript?

**Comment by alexander-heimbuch** [comment]
My wild guess would be that you would have to invoke the function in the constructor since class member declarations are static. Still this doesn't rally integrate nicely with the Vue Class declaration. I think providing decorators for Typescript could be really nice.

**Comment by arunrreddy** [comment]
> My wild guess would be that you would have to invoke the function in the constructor since class member declarations are static. Still this doesn't rally integrate nicely with the Vue Class declaration. I think providing decorators for Typescript could be really nice.

Can you provide a small dirty or hacky example of how this could be implemented without using decorators as of now?

**Comment by alexander-heimbuch** [comment]
Good news everybody, I updated the library to be compatible with Vue 3 and getting the most use out of hooks. I rewrote the lib in TypeScript so this should work now :)
