### ISSUE TITLE
pre-bound this.mapState bug

### ISSUE THREAD

**Issue by smirzo** [alexander-heimbuch/redux-vuex#2]
Firstly, thanks for open-sourcing this library! Saved me a lot of headache!

There seems to be a small bug when trying to map an object with the pre-bound this.mapState function as shown in the README example: 

```js
export default {
  name: 'My Vue Component',
  data () {
    return {
      baz: 10
      ...this.mapState({
        baz: function (state) {
          return state.bar + this.baz //maps state.bar + 10 to data.baz
        }
      })
    }
  }
}
```

Namely, Vue complains that the value has not been defined and looking at the devtools, I can see that it has mapped an object as the object key:

<img width="420" alt="screenshot 2018-10-08 at 13 01 23" src="https://user-images.githubusercontent.com/22012046/46605966-8d3d3180-cafb-11e8-84bd-3fabd8fed931.png">

At first glance, the rest parameters in `mixin.js` seems to be the culprit.
https://github.com/alexander-heimbuch/redux-vuex/blob/fcedee60856d3944e298feb37e75063b4b608c77/src/mixin.js#L24

Replacing it with a simple `props` argument fixes the issue, although I haven't had the chance to look at how it actually affects the mapState function and if it has any side-effects.

**Comment by alexander-heimbuch** [comment]
Hey, thanks for the report :) I think I just made simple stupid typo, this should work:
```javascript
export default {
  name: 'My Vue Component',
  data () {
    return {
      baz: 10
      ...this.mapState({
        bar: function (state) {
          return state.bar + this.baz //maps state.bar + 10 to data.baz
        }
      })
    }
  }
}
```

**Comment by smirzo** [comment]
Hey, thanks for the quick reply! This was my first hunch as well but unfortunately it still resulted in the same error.

Looking at the `map-state.js` file now, it seems that the exported function is already implementing rest parameters, which means that the `this.mapState` props are passed as a double nested array.

https://github.com/alexander-heimbuch/redux-vuex/blob/fcedee60856d3944e298feb37e75063b4b608c77/src/mixin.js#L24
https://github.com/alexander-heimbuch/redux-vuex/blob/fcedee60856d3944e298feb37e75063b4b608c77/src/map-state.js#L37

**Comment by alexander-heimbuch** [comment]
Ahh you are right, will provide a fix today evening :)

**Comment by smirzo** [comment]
Thanks again and have a great day :)

**Comment by alexander-heimbuch** [comment]
@smirzo can you verify if this fix works?
