### ISSUE TITLE
Attribute store conflicts with other frame attributes

### ISSUE THREAD

**Issue by Sayid1** [alexander-heimbuch/redux-vuex#6]
Hi,
The store is a very common attribute that I have been using with other frameworks.

I'm trying to rename the store property and send a new one package

**Comment by alexander-heimbuch** [comment]
Could a configurable property name on the instance an option for you?

**Comment by Sayid1** [comment]
Actually, store is property  of other frameworks, is not configurable

**Comment by Sayid1** [comment]
To avoid conflicts with other frameworks, why not put a  special symbol in front of it?

**Comment by alexander-heimbuch** [comment]
I was referring to introduce a configuration in `redux-vuex` also a prefix won't prevent a potential conflict. So by default the binding would be `this.store`, but you could configure it in the `connect` call, like so:

```
connect({ 
  Vue,
  store,
  binding: 'myStore'
})
```

**Comment by Sayid1** [comment]
https://github.com/alexander-heimbuch/redux-vuex/blob/ec4ff980296d893c0ac0b6f995786f582dfe0f06/src/mixin.js#L21

I see this in the code,

**Comment by alexander-heimbuch** [comment]
Yes, I'm asking you if a configurable store binding would fit your use case. It is not implemented yet.

**Comment by Sayid1** [comment]
Sure,of course. That would be great!

**Comment by weboAp** [comment]
+1

**Comment by alexander-heimbuch** [comment]
released in `0.2.0`
